CREATE TABLE USER_TBL(
    USER_NO     NUMBER          PRIMARY KEY,
    USER_ID     VARCHAR2(20)    UNIQUE NOT NULL,
    USER_PW     CHAR(64)        NOT NULL,
    USER_NAME   VARCHAR2(30)    NOT NULL,
    USER_EMAIL  VARCHAR2(50)    NOT NULL,
    USER_PROFILE    VARCHAR2(200)
);

CREATE SEQUENCE USER_SEQ;

CREATE TABLE LIST_TBL(
    LIST_NO     NUMBER          PRIMARY KEY,
    USER_NO     NUMBER          REFERENCES USER_TBL(USER_NO) ON DELETE CASCADE,
    LIST_NAME   VARCHAR2(50)    NOT NULL,
    LIST_OPEN   NUMBER          DEFAULT 0
);

CREATE SEQUENCE LIST_SEQ;

CREATE TABLE LIST_FAVORITE(
    LIST_NO     NUMBER          REFERENCES LIST_TBL(LIST_NO) ON DELETE CASCADE,
    USER_NO     NUMBER          REFERENCES USER_TBL(USER_NO) ON DELETE CASCADE,
    PRIMARY KEY(LIST_NO, USER_NO)
);

CREATE TABLE KEYWORD_TBL(
    KEYWORD_NO  NUMBER          PRIMARY KEY,
    LIST_NO     NUMBER          REFERENCES LIST_TBL(LIST_NO) ON DELETE CASCADE,
    KEYWORD_NAME    VARCHAR2(30) NOT NULL
);

CREATE SEQUENCE KEYWORD_SEQ;

CREATE TABLE BOOKMARK_TBL(
    MARK_NO     NUMBER      PRIMARY KEY,
    USER_NO     NUMBER      REFERENCES USER_TBL(USER_NO) ON DELETE CASCADE,
    MARK_LINK   VARCHAR2(100),
    MARK_DATE   CHAR(19),
    LIST_NO     NUMBER      REFERENCES LIST_TBL(LIST_NO) ON DELETE SET NULL,
    MARK_DETAIL    VARCHAR2(100)
);

CREATE SEQUENCE BOOKMARK_SEQ;

CREATE TABLE BOOKMARK_KEYWORD(
    KEYWORD_NO      NUMBER      REFERENCES KEYWORD_TBL(KEYWORD_NO) ON DELETE CASCADE,
    MARK_NO         NUMBER     REFERENCES BOOKMARK_TBL(MARK_NO) ON DELETE CASCADE,
    PRIMARY KEY(KEYWORD_NO, MARK_NO)
);
